'use strict';

/**
 * @ngdoc service
 * @name pendesApp.kinkList
 * @description
 * # kinkList
 * Constant in the pendesApp.
 */
angular.module('pendesApp')
.constant('kinkList', 
	  [
		  {
			  categoryCode:"B",
			  categoryTitle:"Bondage & Domination",
			  kinks:[
				  {id:"B1",name:"Behavior"},
        	{id:"B1-1",name:"B & D > Behavior: Begging"},
				  {id:"B1-2",name:"B & D > Behavior: Meek"},
				  {id:"B1-3",name:"B & D > Behavior: Pet Play"},
				  {id:"B1-4",name:"B & D > Behavior: Physical Exhaustion"},
				  {id:"B1-5",name:"B & D > Behavior: Pony Play"},
				  {id:"B1-6",name:"B & D > Behavior: Sexual Exhaustion"},
				  {id:"B1-7",name:"B & D > Behavior: Uppity"},
				  {id:"B2",name:"Bondage"},
				  {id:"B2-1",name:"B & D > Bondage: Belts"},
				  {id:"B2-2",name:"B & D > Bondage: Caging"},
				  {id:"B2-3",name:"B & D > Bondage: Chain"},
				  {id:"B2-4",name:"B & D > Bondage: Contortion"},
				  {id:"B2-5",name:"B & D > Bondage: Devices"},
				  {id:"B2-6",name:"B & D > Bondage: Encasement"},
				  {id:"B2-7",name:"B & D > Bondage: Gags"},
				  {id:"B2-8",name:"B & D > Bondage: Handcuffs"},
				  {id:"B2-9",name:"B & D > Bondage: Immobilization"},
          {id:"B2-10",name:"B & D > Bondage: Leash & Collar"},
				  {id:"B2-11",name:"B & D > Bondage: Magic"},
				  {id:"B2-12",name:"B & D > Bondage: Manacles"},
				  {id:"B2-13",name:"B & D > Bondage: Restraint(Light)"},
				  {id:"B2-14",name:"B & D > Bondage: Restraint(Heavy)"},
				  {id:"B2-15",name:"B & D > Bondage: Rope"},
				  {id:"B2-16",name:"B & D > Bondage: Shibari"},
				  {id:"B2-17",name:"B & D > Bondage: Suspension"},
				  {id:"B3",name:"Rules"},
				  {id:"B3-1",name:"B & D > Rules: Access Restrictions"},
				  {id:"B3-2",name:"B & D > Rules: Clothing Restriction"},
				  {id:"B3-3",name:"B & D > Rules: Chastity"},
				  {id:"B3-4",name:"B & D > Rules: Humiliation"},
				  {id:"B3-5",name:"B & D > Rules: Movement Restriction"},
				  {id:"B3-6",name:"B & D > Rules: Orgasm Control"},
				  {id:"B3-7",name:"B & D > Rules: Orgasm Denial"},
				  {id:"B3-8",name:"B & D > Rules: Speech Restraints"},
				  {id:"B4",name:"Sensory Deprivation"},
				  {id:"B4-1",name:"B & D > Sensory Deprivation: Blindfolds"},
				  {id:"B4-2",name:"B & D > Sensory Deprivation: Earplugs"},
				  {id:"B4-3",name:"B & D > Sensory Deprivation: Full Body"},
				  {id:"B4-4",name:"B & D > Sensory Deprivation: Hoods"},
				  {id:"B4-5",name:"B & D > Sensory Deprivation: Masks"},
				  {id:"B4-6",name:"B & D > Sensory Deprivation: Numbing"},
				  {id:"B5",name:"Slavery"},
				  {id:"B5-1",name:"B & D > Slavery: Branding"},
				  {id:"B5-2",name:"B & D > Slavery: Discipline"},
				  {id:"B5-3",name:"B & D > Slavery: Harem"},
				  {id:"B5-4",name:"B & D > Slavery: Objectification"},
				  {id:"B5-5",name:"B & D > Slavery: Pet"},
				  {id:"B5-6",name:"B & D > Slavery: Slave"}
			  ]
		  },
		  {
			  categoryCode:"H",
			  categoryTitle:"Hardplay",
			  kinks:[
				  {id:"H1",name:"Amputation"},
				  {id:"H1-1",name:"Hard Play > Amputation: Clean"},
				  {id:"H1-2",name:"Hard Play > Amputation: Realistic"},
				  {id:"H2",name:"Blood"},
				  {id:"H2-1",name:"Hard Play > Blood: Bloodletting"},
				  {id:"H2-2",name:"Hard Play > Blood: Swallowing"},
				  {id:"H3",name:"Breath Control"},
				  {id:"H3-1",name:"Hard Play > Breath Control: Asphyxiation"},
				  {id:"H3-2",name:"Hard Play > Breath Control: Choking"},
				  {id:"H4",name:"Death"},
				  {id:"H4-1",name:"Hard Play > Death: Defilement"},
				  {id:"H4-2",name:"Hard Play > Death: Impalement"},
				  {id:"H4-3",name:"Hard Play > Death: Permanent"},
				  {id:"H5",name:"Drugs"},
				  {id:"H5-1",name:"Hard Play > Drugs: Addiction"},
				  {id:"H5-2",name:"Hard Play > Drugs: Alcohol"},
				  {id:"H5-3",name:"Hard Play > Drugs: Aphrodisiacs"},
				  {id:"H5-4",name:"Hard Play > Drugs: Hard Drugs"},
				  {id:"H5-5",name:"Hard Play > Drugs: Smoking"},
				  {id:"H6",name:"Enema"},
				  {id:"H6-1",name:"Hard Play > Enema: Clean"},
				  {id:"H6-2",name:"Hard Play > Enema: Cum"},
				  {id:"H6-3",name:"Hard Play > Enema: Messy"},
				  {id:"H7",name:"Inflation"},
				  {id:"H7-1",name:"Hard Play > Inflation: Heavy"},
				  {id:"H7-2",name:"Hard Play > Inflation: Light"},
				  {id:"H7-3",name:"Hard Play > Inflation: Popping"},
				  {id:"H8",name:"Rape"},
				  {id:"H8-1",name:"Hard Play > Rape: Hard Rape"},
				  {id:"H8-2",name:"Hard Play > Rape: Pseudo-Rape"},
				  {id:"H9",name:"Torture"},
				  {id:"H9-1",name:"Hard Play > Torture: Breast/Nipple"},
				  {id:"H9-2",name:"Hard Play > Torture: Burning"},
				  {id:"H9-3",name:"Hard Play > Torture: Chemical"},
				  {id:"H9-4",name:"Hard Play > Torture: Electro-Torture"},
				  {id:"H9-5",name:"Hard Play > Torture: Genital Torture"},
				  {id:"H9-6",name:"Hard Play > Torture: Hot/Cold"},
				  {id:"H9-7",name:"Hard Play > Torture: Pain"},
				  {id:"H9-8",name:"Hard Play > Torture: Sexual"},
				  {id:"H9-9",name:"Hard Play > Torture: Starvation"},
          {id:"H10",name:"Messy"},
				  {id:"H10-1",name:"Hard Play > Messy: Menses"},
				  {id:"H10-2",name:"Hard Play > Messy: Musk"},
				  {id:"H10-3",name:"Hard Play > Messy: Slob"},
				  {id:"H10-4",name:"Hard Play > Messy: Smegma"},
				  {id:"H10-5",name:"Hard Play > Messy: Wet and Messy"},
				  {id:"H11",name:"Mutilation"},
				  {id:"H11-1",name:"Hard Play > Mutilation: Abrasions"},
				  {id:"H11-2",name:"Hard Play > Mutilation: Branding"},
				  {id:"H11-3",name:"Hard Play > Mutilation: Castration"},
				  {id:"H11-4",name:"Hard Play > Mutilation: Piercing"},
				  {id:"H11-5",name:"Hard Play > Mutilation: Scarring"},
				  {id:"H11-6",name:"Hard Play > Mutilation: Tattoos"},
				  {id:"H12",name:"Necrophilia"},
				  {id:"H13",name:"Scat"},
				  {id:"H13-1",name:"Hard Play > Scat: Diapers"},
				  {id:"H13-2",name:"Hard Play > Scat: Farting"},
				  {id:"H13-3",name:"Hard Play > Scat: Feces Play"},
				  {id:"H13-4",name:"Hard Play > Scat: Hyper Scat"},
				  {id:"H13-5",name:"Hard Play > Scat: Scat Torture"},
				  {id:"H13-6",name:"Hard Play > Scat: Soiling"},
				  {id:"H13-7",name:"Hard Play > Scat: Swallowing"},
				  {id:"H14",name:"Transformation"},
				  {id:"H14-1",name:"Hard Play > Transformation: Addition"},
				  {id:"H14-2",name:"Hard Play > Transformation: Age Progression"},
				  {id:"H14-3",name:"Hard Play > Transformation: Age Regression"},
				  {id:"H14-4",name:"Hard Play > Transformation: Animal"},
				  {id:"H14-5",name:"Hard Play > Transformation: Anthro"},
				  {id:"H14-6",name:"Hard Play > Transformation: Bimbo"},
				  {id:"H14-7",name:"Hard Play > Transformation: Desexualization"},
				  {id:"H14-8",name:"Hard Play > Transformation: Dollification"},
				  {id:"H14-9",name:"Hard Play > Transformation: Enhancement"},
          {id:"H14-10",name:"Hard Play > Transformation: Expansion"},
				  {id:"H14-11",name:"Hard Play > Transformation: Fast"},
				  {id:"H14-12",name:"Hard Play > Transformation: Fatal"},
				  {id:"H14-13",name:"Hard Play > Transformation: Forced"},
				  {id:"H14-14",name:"Hard Play > Transformation: Growth"},
				  {id:"H14-15",name:"Hard Play > Transformation: Inanimate"},
				  {id:"H14-16",name:"Hard Play > Transformation: Mental"},
				  {id:"H14-17",name:"Hard Play > Transformation: Merging"},
				  {id:"H14-18",name:"Hard Play > Transformation: Permanent"},
				  {id:"H14-19",name:"Hard Play > Transformation: Petrification"},
				  {id:"H14-20",name:"Hard Play > Transformation: Removal"},
				  {id:"H14-21",name:"Hard Play > Transformation: Rubber/Latex"},
				  {id:"H14-22",name:"Hard Play > Transformation: Sex"},
				  {id:"H14-23",name:"Hard Play > Transformation: Shrinking"},
				  {id:"H14-24",name:"Hard Play > Transformation: Slow"},
				  {id:"H14-25",name:"Hard Play > Transformation: Theft"},
				  {id:"H14-26",name:"Hard Play > Transformation: Weird"},
				  {id:"H15",name:"Vomit"},
				  {id:"H15-1",name:"Hard Play > Vomit: Swallowing"},
				  {id:"H16",name:"Vore"},
				  {id:"H16-1",name:"Hard Play > Vore: Absorption"},
				  {id:"H16-2",name:"Hard Play > Vore: Alternative Vore"},
				  {id:"H16-3",name:"Hard Play > Vore: Anal Vore"},
				  {id:"H16-4",name:"Hard Play > Vore: Being Predator"},
				  {id:"H16-5",name:"Hard Play > Vore: Being Prey"},
				  {id:"H16-6",name:"Hard Play > Vore: Breast Vore"},
				  {id:"H16-7",name:"Hard Play > Vore: Cannibalism"},
				  {id:"H16-8",name:"Hard Play > Vore: Cock Vore"},
				  {id:"H16-9",name:"Hard Play > Vore: Cooking"},
				  {id:"H16-10",name:"Hard Play > Vore: Digestion"},
				  {id:"H16-11",name:"Hard Play > Vore: Disposal"},
				  {id:"H16-12",name:"Hard Play > Vore: Hard Vore"},
				  {id:"H16-13",name:"Hard Play > Vore: Realistic Vore"},
				  {id:"H16-14",name:"Hard Play > Vore: Soft Vore"},
				  {id:"H16-15",name:"Hard Play > Vore: Soul Vore"},
				  {id:"H16-16",name:"Hard Play > Vore: Unbirthing"},
				  {id:"H16-17",name:"Hard Play > Vore: Unrealistic Vore"},
				  {id:"H17",name:"Watersports"},
				  {id:"H17-1",name:"Hard Play > Watersports: Bathroom Control"},
				  {id:"H17-2",name:"Hard Play > Watersports: hroom Play"},
				  {id:"H17-3",name:"Hard Play > Watersports: Diapers"},
				  {id:"H17-4",name:"Hard Play > Watersports: Hyper Watersports"},
				  {id:"H17-5",name:"Hard Play > Watersports: Marking"},
				  {id:"H17-6",name:"Hard Play > Watersports: Piss Enema"},
				  {id:"H17-7",name:"Hard Play > Watersports: Swallowing"},
				  {id:"H17-8",name:"Hard Play > Watersports: Voyeur"},
				  {id:"H17-9",name:"Hard Play > Watersports: Wetting"}

			  ]
		  },
		  {
			  categoryCode:"M",
			  categoryTitle:"Role",
			  kinks:[
				  {id:"M1",name:"Role: Bottom"},
				  {id:"M2",name:"Role: Dominant"},
				  {id:"M3",name:"Role: Equal"},
				  {id:"M4",name:"Role: Submissive"},
				  {id:"M5",name:"Role: Switch"},
				  {id:"M6",name:"Role: Top"}
			  ]
		  },
		  {
			  categoryCode:"P",
			  categoryTitle:"Preference",
			  kinks:[
				  {id:"P1",name:"Preference: Androgynous"},
				  {id:"P1-1",name:"Preference: Trap"},
				  {id:"P1-2",name:"Preference: Reverse-Trap"},
				  {id:"P2",name:"Preference: Cuntboys"},
				  {id:"P3",name:"Preference: Females"},
				  {id:"P4",name:"Preference: Hermaphrodites"},
				  {id:"P5",name:"Preference: Male Herms"},
				  {id:"P6",name:"Preference: Males"},
				  {id:"P7",name:"Preference: Shemales"},
				  {id:"P8",name:"Preference: Transgender"}
			  ]
		  },
		  {
			  categoryCode:"R",
			  categoryTitle:"Roleplay",
			  kinks:[
				  {id:"R1",name:"Clothing"},
				  {id:"R1-1",name:"Roleplay > Clothing: Boots/Shoes"},
				  {id:"R1-2",name:"Roleplay > Clothing: Costumes"},
				  {id:"R1-3",name:"Roleplay > Clothing: Crossdressing"},
				  {id:"R1-4",name:"Roleplay > Clothing: Glasses"},
				  {id:"R1-5",name:"Roleplay > Clothing: Kimono/Japanese"},
				  {id:"R1-6",name:"Roleplay > Clothing: Latex"},
				  {id:"R1-7",name:"Roleplay > Clothing: Leather"},
				  {id:"R1-8",name:"Roleplay > Clothing: Lingerie"},
				  {id:"R1-9",name:"Roleplay > Clothing: Masks"},
          {id:"R1-10",name:"Roleplay > Clothing: Maid"},
				  {id:"R1-11",name:"Roleplay > Clothing: Naked Apron"},
				  {id:"R1-12",name:"Roleplay > Clothing: Religious"},
				  {id:"R1-13",name:"Roleplay > Clothing: Slutty"},
				  {id:"R1-14",name:"Roleplay > Clothing: Style"},
				  {id:"R1-15",name:"Roleplay > Clothing: Suits"},
				  {id:"R1-16",name:"Roleplay > Clothing: Underwear"},
				  {id:"R1-17",name:"Roleplay > Clothing: Uniforms"},
				  {id:"R1-18",name:"Roleplay > Clothing: Wedding/Formal"},
				  {id:"R1-19",name:"Roleplay > Clothing: Stockings"},
				  {id:"R2",name:"Exhibitionism"},
				  {id:"R2-1",name:"Exhibitionism - Public Nudity"},
				  {id:"R2-2",name:"Exhibitionism - Public Sex"},
				  {id:"R3",name:"Food"},
				  {id:"R3-1",name:"Roleplay > Food: Force Feeding"},
				  {id:"R3-2",name:"Roleplay > Food: Nyo/Nan-taimori"},
				  {id:"R3-3",name:"Roleplay > Food: Sweets"},
				  {id:"R3-4",name:"Roleplay > Food: Syrups"},
				  {id:"R3-5",name:"Roleplay > Food: Weight Gain"},
				  {id:"R4",name:"Instant Hookups"},
				  {id:"R5",name:"Long Term"},
				  {id:"R5-1",name:"Roleplay > Long Term: Grid"},
				  {id:"R5-2",name:"Roleplay > Long Term: Sandbox"},
				  {id:"R6",name:"Magic"},
				  {id:"R6-1",name:"Roleplay > Magic: Background"},
				  {id:"R6-2",name:"Roleplay > Magic: Magic Sex"},
				  {id:"R6-3",name:"Roleplay > Magic: Potions"},
				  {id:"R7",name:"Mind Control"},
				  {id:"R7-1",name:"Roleplay > Mind Control: Body Control"},
				  {id:"R7-2",name:"Roleplay > Mind Control: Direct Control"},
				  {id:"R7-3",name:"Roleplay > Mind Control: Hypnotism"},
				  {id:"R7-4",name:"Roleplay > Mind Control: Memory Wipe"},
				  {id:"R7-5",name:"Roleplay > Mind Control: Programming"},
				  {id:"R7-6",name:"Roleplay > Mind Control: Suggestion"},
				  {id:"R7-7",name:"Roleplay > Mind Control: Training"},
				  {id:"R8",name:"Nonsexual"},
				  {id:"R9",name:"Perspective - First"},
				  {id:"R10",name:"Perspective - Second"},
				  {id:"R11",name:"Perspective - Third"},
          {id:"R12",name:"Pregnancy"},
          {id:"R12-1",name:"Roleplay > Pregnancy: Birthing"},
				  {id:"R12-2",name:"Roleplay > Pregnancy: Breeding"},
				  {id:"R12-3",name:"Roleplay > Pregnancy: Extreme Pregnancy"},
				  {id:"R12-4",name:"Roleplay > Pregnancy: Impregnation"},
				  {id:"R12-5",name:"Roleplay > Pregnancy: Male Pregnancy"},
				  {id:"R12-6",name:"Roleplay > Pregnancy: Oviposition"},
				  {id:"R12-7",name:"Roleplay > Pregnancy: Pregnant Sex"},
				  {id:"R12-8",name:"Roleplay > Pregnancy: Risk of Pregnancy"},
				  {id:"R12-9",name:"Roleplay > Pregnancy: Unusual Pregnancy"},
				  {id:"R13",name:"Role Reversal"},
          {id:"R14",name:"Romance"},
          {id:"R14-1",name:"Roleplay > Romance: Cuddling"},
				  {id:"R14-2",name:"Roleplay > Romance: Dating"},
				  {id:"R14-3",name:"Roleplay > Romance: Kissing"},
				  {id:"R14-4",name:"Roleplay > Romance: Marriage"},
				  {id:"R14-5",name:"Roleplay > Romance: PDA"},
				  {id:"R14-6",name:"Roleplay > Romance: Polygamy"},
				  {id:"R15",name:"RP in RP"},
          {id:"R15-1",name:"Roleplay > RP in RP: Ageplay"},
				  {id:"R15-2",name:"Roleplay > RP in RP: Costumes"},
				  {id:"R15-3",name:"Roleplay > RP in RP: Infantilism"},
				  {id:"R16",name:"Rubber/Latex"},
				  {id:"R16-1",name:"Roleplay > Rubber/Latex: Hoods"},
				  {id:"R16-2",name:"Roleplay > Rubber/Latex: Suits"},
				  {id:"R16-3",name:"Roleplay > Rubber/Latex: Toys"},
				  {id:"R17",name:"Sandboxing"},
          {id:"R18",name:"Taboo"},
				  {id:"R18-1",name:"Roleplay > Taboo: Adultery"},
				  {id:"R18-2",name:"Roleplay > Taboo: Age Differences"},
				  {id:"R18-3",name:"Roleplay > Taboo: Blasphemy"},
				  {id:"R18-4",name:"Roleplay > Taboo: Incest"},
				  {id:"R18-5",name:"Roleplay > Taboo: Interracial"},
				  {id:"R18-6",name:"Roleplay > Taboo: Interspecies"},
				  {id:"R18-7",name:"Roleplay > Taboo: Orientation Play"},
				  {id:"R18-8",name:"Roleplay > Taboo: Spanking"},
				  {id:"R19",name:"Teasing"},
          {id:"R19-1",name:"Roleplay > Teasing: Caressing"},
				  {id:"R19-2",name:"Roleplay > Teasing: Humiliation"},
				  {id:"R19-3",name:"Roleplay > Teasing: Tickling"},
          {id:"R20",name:"Themed"},
				  {id:"R20-1",name:"Roleplay > Themed: Captivity"},
				  {id:"R20-2",name:"Roleplay > Themed: Fantasy"},
				  {id:"R20-3",name:"Roleplay > Themed: Isolation"},
				  {id:"R20-4",name:"Roleplay > Themed: Law Enforcement"},
				  {id:"R20-5",name:"Roleplay > Themed: Medical"},
				  {id:"R20-6",name:"Roleplay > Themed: Office"},
				  {id:"R20-7",name:"Roleplay > Themed: Political"},
				  {id:"R20-8",name:"Roleplay > Themed: Prostitution"},
				  {id:"R20-9",name:"Roleplay > Themed: Religion"},
          {id:"R20-10",name:"Roleplay > Themed: School"},
				  {id:"R20-11",name:"Roleplay > Themed: Sci-Fi"},
				  {id:"R20-12",name:"Roleplay > Themed: Steampunk"},
				  {id:"R20-13",name:"Roleplay > Themed: Tribal"},
				  {id:"R20-14",name:"Roleplay > Themed: Zero-G"},
				  {id:"R21",name:"Unwilling"},
          {id:"R21-1",name:"Roleplay > Unwilling: Blackmail"},
				  {id:"R21-2",name:"Roleplay > Unwilling: Obligation"},
				  {id:"R21-3",name:"Roleplay > Unwilling: Penalty"},
				  {id:"R22",name:"Violence"},
				  {id:"R22-1",name:"Roleplay > Violence: Bladeplay"},
				  {id:"R22-2",name:"Roleplay > Violence: Fighting"},
				  {id:"R22-3",name:"Roleplay > Violence: Guns"},
				  {id:"R22-4",name:"Roleplay > Violence: Wrestling"},
				  {id:"R23",name:"Voyeurism"},
				  {id:"R23-1",name:"Roleplay > Voyeurism: Accidental"},
				  {id:"R23-2",name:"Roleplay > Voyeurism: Cuckolding"},
				  {id:"R23-3",name:"Roleplay > Voyeurism: Spying"},
          
			  ]
		  },
		  {
			  categoryCode:"S",
			  categoryTitle:"Sex",
			  kinks:[
				  {id:"S1",name:"Anal Sex"},
				  {id:"S1-1",name:"Sex > Anal: Ass Worship"},
				  {id:"S1-2",name:"Sex > Anal: Fisting"},
          {id:"S1-3",name:"Sex > Anal: Gaping"},
          {id:"S1-4",name:"Sex > Anal: Hotdogging"},
				  {id:"S1-5",name:"Sex > Anal: Pegging"},
				  {id:"S1-6",name:"Sex > Anal: Penetration"},
				  {id:"S1-7",name:"Sex > Anal: Rimming"},
				  {id:"S1-8",name:"Sex > Anal: Training"},
				  {id:"S1-9",name:"Sex > Anal: Virginity"},
				  {id:"S2",name:"Biting"},
				  {id:"S2-1",name:"Sex > Biting: Marking"},
				  {id:"S3",name:"Breasts"},
				  {id:"S3-1",name:"Sex > Breasts: Breast Worship"},
				  {id:"S3-2",name:"Sex > Breasts: Docking"},
				  {id:"S3-3",name:"Sex > Breasts: Fondling"},
				  {id:"S3-4",name:"Sex > Breasts: Lactation"},
				  {id:"S3-5",name:"Sex > Breasts: Nipple Penetration"},
				  {id:"S3-6",name:"Sex > Breasts: Titfucking"},
				  {id:"S4",name:"Clothed Sex"},
				  {id:"S5",name:"Condoms"},
				  {id:"S5-1",name:"Sex > Condoms: Breaking"},
				  {id:"S5-2",name:"Sex > Condoms: Swallowing After"},
				  {id:"S6",name:"Cumplay"},
				  {id:"S6-1",name:"Sex > Cumplay: Bukkake"},
				  {id:"S6-2",name:"Sex > Cumplay: Cum Bath"},
				  {id:"S6-3",name:"Sex > Cumplay: Cum Diet"},
				  {id:"S6-4",name:"Sex > Cumplay: Inflation(Light)"},
				  {id:"S6-5",name:"Sex > Cumplay: Inflation(Medium)"},
				  {id:"S6-6",name:"Sex > Cumplay: Inflation(Heavy)"},
				  {id:"S6-7",name:"Sex > Cumplay: Large Quantities"},
				  {id:"S6-8",name:"Sex > Cumplay: Swallowing"},
				  {id:"S6-9",name:"Sex > Cumplay: Unusual Semen"},
          {id:"S6-10",name:"Sex > Cumplay: Creampie"},
				  {id:"S6-11",name:"Sex > Cumplay: Internal"},
				  {id:"S7",name:"Exotic"},
				  {id:"S7-1",name:"Sex > Exotic: Armpit Sex"},
				  {id:"S7-2",name:"Sex > Exotic: Ear Penetration"},
				  {id:"S7-3",name:"Sex > Exotic: Ear Play"},
				  {id:"S7-4",name:"Sex > Exotic: Eye Penetration"},
				  {id:"S7-5",name:"Sex > Exotic: Foot Fetish"},
				  {id:"S7-6",name:"Sex > Exotic:- Footjobs"},
				  {id:"S7-7",name:"Sex > Exotic: Hairjob"},
				  {id:"S7-8",name:"Sex > Exotic: Navel Penetration"},
				  {id:"S7-9",name:"Sex > Exotic: Navel Play"},
				  {id:"S7-10",name:"Sex > Exotic: Other"},
				  {id:"S7-11",name:"Sex > Exotic: Sleep Sex"},
				  {id:"S8",name:"Masturbation"},
				  {id:"S8-1",name:"Sex > Masturbation: In Scenes"},
				  {id:"S8-2",name:"Sex > Masturbation: Mutual Masturbation"},
				  {id:"S8-3",name:"Sex > Masturbation: Secret"},
				  {id:"S9",name:"Multiple Penetration"},
				  {id:"S9-1",name:"Sex > Multiple Penetration: 3+ Penetration"},
				  {id:"S9-2",name:"Sex > Multiple Penetration: All The Way Through"},
				  {id:"S9-3",name:"Sex > Multiple Penetration: Double Penetration"},
				  {id:"S9-4",name:"Sex > Multiple Penetration: Gangbang"},
          {id:"S10",name:"Oral Sex"},
				  {id:"S10-1",name:"Sex > Oral: Autocunnilingus"},
				  {id:"S10-2",name:"Sex > Oral: Autofellatio"},
				  {id:"S10-3",name:"Sex > Oral: Cunnilingus"},
				  {id:"S10-4",name:"Sex > Oral: Face-Fucking"},
				  {id:"S10-5",name:"Sex > Oral: Fellatio"},
				  {id:"S10-6",name:"Sex > Oral: Throat Penetration"},
				  {id:"S10-7",name:"Sex > Oral: Virginity"},
				  {id:"S11",name:"Penis Sex"},
				  {id:"S11-1",name:"Sex > Penis: Docking"},
				  {id:"S11-2",name:"Sex > Penis: Frottage"},
				  {id:"S11-3",name:"Sex > Penis: Handjob"},
				  {id:"S11-4",name:"Sex > Penis: Sounding"},
				  {id:"S11-5",name:"Sex > Penis: Cock Worship"},
				  {id:"S11-6",name:"Sex > Penis: Ball Worship"},
				  {id:"S12",name:"Toys"},
				  {id:"S12-1",name:"Sex > Toys: Anal Beads"},
				  {id:"S12-2",name:"Sex > Toys: Dildos"},
				  {id:"S12-3",name:"Sex > Toys: Sex Machines"},
				  {id:"S12-4",name:"Sex > Toys: Strap-ons"},
				  {id:"S12-5",name:"Sex > Toys: Vibrators"},
				  {id:"S13",name:"Vaginal Sex"},
				  {id:"S13-1",name:"Sex > Vaginal: Cervical Penetration"},
				  {id:"S13-2",name:"Sex > Vaginal: Fingering"},
				  {id:"S13-3",name:"Sex > Vaginal: Fisting"},
				  {id:"S13-4",name:"Sex > Vaginal: Gaping"},
				  {id:"S13-5",name:"Sex > Vaginal: Penetration"},
				  {id:"S13-6",name:"Sex > Vaginal: Pussy Worship"},
				  {id:"S13-7",name:"Sex > Vaginal: Squirting"},
				  {id:"S13-8",name:"Sex > Vaginal: Tribadism"},
				  {id:"S13-9",name:"Sex > Vaginal: Urethra Penetration"},
          {id:"S13-10",name:"Sex > Vaginal: Virginity"},

			  ]
		  },
		  {
			  categoryCode:"T",
			  categoryTitle:"Body Types",
			  kinks:[
				  {id:"T1",name:"Animal"},
				  {id:"T1-1",name:"Body Types > Animal: Aquatic"},
				  {id:"T1-2",name:"Body Types > Animal: Avian"},
				  {id:"T1-3",name:"Body Types > Animal: Draconic"},
				  {id:"T1-4",name:"Body Types > Animal: Equine"},
				  {id:"T1-5",name:"Body Types > Animal: Insect/Arachnid"},
				  {id:"T1-6",name:"Body Types > Animal: Pokemon/Digimon"},
				  {id:"T1-7",name:"Body Types > Animal: Quadruped"},
				  {id:"T1-8",name:"Body Types > Animal: Serpentine"},
				  {id:"T2",name:"Animal Anatomy"},
				  {id:"T2-1",name:"Body Types > Animal Anatomy: Barbed Cocks"},
				  {id:"T2-2",name:"Body Types > Animal Anatomy: Bestial Cocks"},
				  {id:"T2-3",name:"Body Types > Animal Anatomy: Knotted Cocks"},
				  {id:"T2-4",name:"Body Types > Animal Anatomy: Sheaths"},
          {id:"T2-5",name:"Body Types > Animal Anatomy: Udders"},
				  {id:"T3",name:"Anthro"},
				  {id:"T3-1",name:"Body Types > Anthro: Equine"},
				  {id:"T3-2",name:"Body Types > Anthro: Feathers"},
				  {id:"T3-3",name:"Body Types > Anthro: Fur"},
				  {id:"T3-4",name:"Body Types > Anthro: Kemonomimi"},
				  {id:"T3-5",name:"Body Types > Anthro: Muzzles"},
				  {id:"T3-6",name:"Body Types > Anthro: Pokemorph"},
				  {id:"T3-7",name:"Body Types > Anthro: Scales"},
				  {id:"T4",name:"Artificial"},
				  {id:"T4-1",name:"Body Types > Artificial: Dolljoints"},
				  {id:"T4-2",name:"Body Types > Artificial: Robots/Cyborgs"},
				  {id:"T5",name:"Elderly Partners"},
				  {id:"T5-1",name:"Body Types > Elderly Partners: Middle Age"},
				  {id:"T5-2",name:"Body Types > Elderly Partners: Elderly"},
				  {id:"T6",name:"Exotic Anatomy"},
				  {id:"T6-1",name:"Body Types > Exotic Anatomy: Dicknipples"},
				  {id:"T6-2",name:"Body Types > Exotic Anatomy: Heterochromia"},
				  {id:"T6-3",name:"Body Types > Exotic Anatomy: Missing Parts"},
				  {id:"T6-4",name:"Body Types > Exotic Anatomy: Multiple Breasts"},
				  {id:"T6-5",name:"Body Types > Exotic Anatomy: Multiple Genitalia"},
				  {id:"T6-6",name:"Body Types > Exotic Anatomy: Out of Place"},
				  {id:"T6-7",name:"Body Types > Exotic Anatomy: Prehensile Cocks"},
				  {id:"T7",name:"Exotic Material"},
				  {id:"T7-1",name:"Body Types > Exotic Material: Ghostly"},
				  {id:"T7-2",name:"Body Types > Exotic Material: Latex"},
				  {id:"T7-3",name:"Body Types > Exotic Material: Metal"},
				  {id:"T7-4",name:"Body Types > Exotic Material: Rubber"},
				  {id:"T7-5",name:"Body Types > Exotic Material: Stone"},
				  {id:"T7-6",name:"Body Types > Exotic Material: Water/Liquid"},
				  {id:"T8",name:"Exotic Species"},
				  {id:"T8-1",name:"Body Types > Exotic Species: Alien/Xeno"},
				  {id:"T8-2",name:"Body Types > Exotic Species: Blob"},
				  {id:"T8-3",name:"Body Types > Exotic Species: Eldritch"},
				  {id:"T8-4",name:"Body Types > Exotic Species: Fantastical"},
				  {id:"T8-5",name:"Body Types > Exotic Species: Monstrous"},
				  {id:"T8-6",name:"Body Types > Exotic Species: Plants"},
				  {id:"T9",name:"Extreme Anatomy"},
				  {id:"T9-1",name:"Body Types > Extreme Anatomy: Huge Ass"},
				  {id:"T9-2",name:"Body Types > Extreme Anatomy: Massive Breasts"},
				  {id:"T9-3",name:"Body Types > Extreme Anatomy: Massive Cocks"},
				  {id:"T9-4",name:"Body Types > Extreme Anatomy: Obesity"},
          {id:"T10",name:"Giant/Macro"},
				  {id:"T11",name:"Head Hair"},
				  {id:"T11-1",name:"Body Types > Head Hair: Bald"},
				  {id:"T11-2",name:"Body Types > Head Hair: Short"},
				  {id:"T11-3",name:"Body Types > Head Hair: Long"},
				  {id:"T11-4",name:"Body Types > Head Hair: Very Long"},
				  {id:"T11-5",name:"Body Types > Head Hair: Exotic"},
				  {id:"T12",name:"Hirsute"},
				  {id:"T12-1",name:"Body Types > Hirsute: Armpit Hair"},
				  {id:"T12-2",name:"Body Types > Hirsute: Beards"},
				  {id:"T12-3",name:"Body Types > Hirsute: Body Hair"},
				  {id:"T12-4",name:"Body Types > Hirsute: Pubic Hair"},
				  {id:"T13",name:"Humanoid"},
				  {id:"T13-1",name:"Body Types > Humanoid: Angel"},
				  {id:"T13-2",name:"Body Types > Humanoid: Demon"},
				  {id:"T13-3",name:"Body Types > Humanoid: Elvish"},
				  {id:"T13-4",name:"Body Types > Humanoid: Human"},
				  {id:"T14",name:"Large Anatomy"},
				  {id:"T14-1",name:"Body Types > Large Anatomy: Chubby"},
				  {id:"T14-2",name:"Body Types > Large Anatomy: Large Asses"},
				  {id:"T14-3",name:"Body Types > Large Anatomy: Large Balls"},
				  {id:"T14-4",name:"Body Types > Large Anatomy: Large Breasts"},
				  {id:"T14-5",name:"Body Types > Large Anatomy: Large Cocks"},
				  {id:"T14-6",name:"Body Types > Large Anatomy: Muscle"},
				  {id:"T15",name:"Sexless"},
				  {id:"T15-1",name:"Body Types > Sexless: Desexed"},
				  {id:"T15-2",name:"Body Types > Sexless: Eunuch"},
				  {id:"T16",name:"Shapeshifters"},
				  {id:"T16-1",name:"Body Types > Shapeshifters: Multiple-Form"},
				  {id:"T16-2",name:"Body Types > Shapeshifters: Single-Form"},
				  {id:"T16-3",name:"Body Types > Shapeshifters: Unwilling"},
				  {id:"T16-4",name:"Body Types > Shapeshifters: Willing"},
				  {id:"T17",name:"Small Anatomy"},
				  {id:"T17-1",name:"Body Types > Small Anatomy: Extreme Tightness"},
				  {id:"T17-2",name:"Body Types > Small Anatomy: Flat Chest"},
				  {id:"T17-3",name:"Body Types > Small Anatomy: Small Breasts"},
				  {id:"T17-4",name:"Body Types > Small Anatomy: Small Cocks"},
				  {id:"T18",name:"Tails"},
				  {id:"T18-1",name:"Body Types > Tails: Fluffy"},
				  {id:"T18-2",name:"Body Types > Tails: Prehensile"},
				  {id:"T19",name:"Taurs/Hybrid"},
				  {id:"T19-1",name:"Body Types > Taurs/Hybrid: Aquatic"},
				  {id:"T19-2",name:"Body Types > Taurs/Hybrid: Avian"},
				  {id:"T19-3",name:"Body Types > Taurs/Hybrid: Insect/Arachnid"},
				  {id:"T19-4",name:"Body Types > Taurs/Hybrid: Quadruped"},
				  {id:"T19-5",name:"Body Types > Taurs/Hybrid: Serpentine"},
				  {id:"T20",name:"Tentacles"},
				  {id:"T20-1",name:"Body Types > Tentacles: Consentacles"},
				  {id:"T21",name:"Twins/Clones"},
				  {id:"T22",name:"Wings"},
          {id:"T22-1",name:"Body Types > Wings: Batlike"},
				  {id:"T22-2",name:"Body Types > Wings: Fairy"},
				  {id:"T22-3",name:"Body Types > Wings: Feathery"},
				  {id:"T23",name:"Young Partners"},
				  {id:"T23-1",name:"Body Types > Young Partners: Preteen"},
				  {id:"T23-2",name:"Body Types > Young Partners: Pubescent"},
				  {id:"T23-3",name:"Body Types > Young Partners: Teenage"},
				  {id:"T24",name:"Decorations"},
				  {id:"T24-1",name:"Body Types > Decorations: Marks"},
				  {id:"T24-2",name:"Body Types > Decorations: Scars"},
				  {id:"T24-3",name:"Body Types > Decorations: Paint"},
				  {id:"T24-4",name:"Body Types > Decorations: Piercings"},
				  {id:"T24-5",name:"Body Types > Decorations: Tattoos"}
				  
			  ]
		  }
	  ]
	 );
