'use strict';

/**
 * @ngdoc service
 * @name pendesApp.kinkList
 * @description
 * # kinkList
 * Constant in the pendesApp.
 */
angular.module('pendesApp')
.constant('kinkList', 
	  [
		  {
			  categoryCode:"B",
			  categoryTitle:"Bondage & Domination",
			  kinks:[
				  {id:"B1",name:"Behavior"},
				  {id:"B1-1",name:"Begging"},
				  {id:"B1-2",name:"Meek"},
				  {id:"B1-3",name:"Pet Play"},
				  {id:"B1-4",name:"Physical Exhaustion"},
				  {id:"B1-5",name:"Pony Play"},
				  {id:"B1-6",name:"Sexual Exhaustion"},
				  {id:"B1-7",name:"Uppity"},
				  {id:"B2",name:"Bondage"},
				  {id:"B2-1",name:"Belts"},
				  {id:"B2-10",name:"Leash & Collar"},
				  {id:"B2-11",name:"Magic"},
				  {id:"B2-12",name:"Manacles"},
				  {id:"B2-13",name:"Restraint(Light)"},
				  {id:"B2-14",name:"Restraint(Heavy)"},
				  {id:"B2-15",name:"Rope"},
				  {id:"B2-16",name:"Shibari"},
				  {id:"B2-17",name:"Suspension"},
				  {id:"B2-2",name:"Caging"},
				  {id:"B2-3",name:"Chain"},
				  {id:"B2-4",name:"Contortion"},
				  {id:"B2-5",name:"Devices"},
				  {id:"B2-6",name:"Encasement"},
				  {id:"B2-7",name:"Gags"},
				  {id:"B2-8",name:"Handcuffs"},
				  {id:"B2-9",name:"Immobilization"},
				  {id:"B3",name:"Rules"},
				  {id:"B3-1",name:"Access Restrictions"},
				  {id:"B3-2",name:"Clothing Restriction"},
				  {id:"B3-3",name:"Chastity"},
				  {id:"B3-4",name:"Humiliation"},
				  {id:"B3-5",name:"Movement Restriction"},
				  {id:"B3-6",name:"Orgasm Control"},
				  {id:"B3-7",name:"Orgasm Denial"},
				  {id:"B3-8",name:"Speech Restraints"},
				  {id:"B4",name:"Sensory Deprivation"},
				  {id:"B4-1",name:"Blindfolds"},
				  {id:"B4-2",name:"Earplugs"},
				  {id:"B4-3",name:"Full Body"},
				  {id:"B4-4",name:"Hoods"},
				  {id:"B4-5",name:"Masks"},
				  {id:"B4-6",name:"Numbing"},
				  {id:"B5",name:"Slavery"},
				  {id:"B5-1",name:"Branding"},
				  {id:"B5-2",name:"Discipline"},
				  {id:"B5-3",name:"Harem"},
				  {id:"B5-4",name:"Objectification"},
				  {id:"B5-5",name:"Pet"},
				  {id:"B5-6",name:"Slave"}
			  ]
		  },
		  {
			  categoryCode:"H",
			  categoryTitle:"Hardplay",
			  kinks:[
				  {id:"H1",name:"Amputation"},
				  {id:"H10",name:"Messy"},
				  {id:"H10-1",name:"Menses"},
				  {id:"H10-2",name:"Musk"},
				  {id:"H10-3",name:"Slob"},
				  {id:"H10-4",name:"Smegma"},
				  {id:"H10-5",name:"Wet and Messy"},
				  {id:"H11",name:"Mutilation"},
				  {id:"H1-1",name:"Clean"},
				  {id:"H11-1",name:"Abrasions"},
				  {id:"H11-2",name:"Branding"},
				  {id:"H11-3",name:"Castration"},
				  {id:"H11-4",name:"Piercing"},
				  {id:"H11-5",name:"Scarring"},
				  {id:"H11-6",name:"Tattoos"},
				  {id:"H12",name:"Necrophilia"},
				  {id:"H1-2",name:"Realistic"},
				  {id:"H13",name:"Scat"},
				  {id:"H13-1",name:"Diapers"},
				  {id:"H13-2",name:"Farting"},
				  {id:"H13-3",name:"Feces Play"},
				  {id:"H13-4",name:"Hyper Scat"},
				  {id:"H13-5",name:"Scat Torture"},
				  {id:"H13-6",name:"Soiling"},
				  {id:"H13-7",name:"Swallowing"},
				  {id:"H14",name:"Transformation"},
				  {id:"H14-1",name:"Addition"},
				  {id:"H14-10",name:"Expansion"},
				  {id:"H14-11",name:"Fast"},
				  {id:"H14-12",name:"Fatal"},
				  {id:"H14-13",name:"Forced"},
				  {id:"H14-14",name:"Growth"},
				  {id:"H14-15",name:"Inanimate"},
				  {id:"H14-16",name:"Mental"},
				  {id:"H14-17",name:"Merging"},
				  {id:"H14-18",name:"Permanent"},
				  {id:"H14-19",name:"Petrification"},
				  {id:"H14-2",name:"Age Progression"},
				  {id:"H14-20",name:"Removal"},
				  {id:"H14-21",name:"Rubber/Latex"},
				  {id:"H14-22",name:"Sex"},
				  {id:"H14-23",name:"Shrinking"},
				  {id:"H14-24",name:"Slow"},
				  {id:"H14-25",name:"Theft"},
				  {id:"H14-26",name:"Weird"},
				  {id:"H14-3",name:"Age Regression"},
				  {id:"H14-4",name:"Animal"},
				  {id:"H14-5",name:"Anthro"},
				  {id:"H14-6",name:"Bimbo"},
				  {id:"H14-7",name:"Desexualization"},
				  {id:"H14-8",name:"Dollification"},
				  {id:"H14-9",name:"Enhancement"},
				  {id:"H15",name:"Vomit"},
				  {id:"H15-1",name:"Swallowing"},
				  {id:"H16",name:"Vore"},
				  {id:"H16-1",name:"Absorption"},
				  {id:"H16-10",name:"Digestion"},
				  {id:"H16-11",name:"Disposal"},
				  {id:"H16-12",name:"Hard Vore"},
				  {id:"H16-13",name:"Realistic Vore"},
				  {id:"H16-14",name:"Soft Vore"},
				  {id:"H16-15",name:"Soul Vore"},
				  {id:"H16-16",name:"Unbirthing"},
				  {id:"H16-17",name:"Unrealistic Vore"},
				  {id:"H16-2",name:"Alternative Vore"},
				  {id:"H16-3",name:"Anal Vore"},
				  {id:"H16-4",name:"Being Predator"},
				  {id:"H16-5",name:"Being Prey"},
				  {id:"H16-6",name:"Breast Vore"},
				  {id:"H16-7",name:"Cannibalism"},
				  {id:"H16-8",name:"Cock Vore"},
				  {id:"H16-9",name:"Cooking"},
				  {id:"H17",name:"Watersports"},
				  {id:"H17-1",name:"Bathroom Control"},
				  {id:"H17-2",name:"Bathroom Play"},
				  {id:"H17-3",name:"Diapers"},
				  {id:"H17-4",name:"Hyper Watersports"},
				  {id:"H17-5",name:"Marking"},
				  {id:"H17-6",name:"Piss Enema"},
				  {id:"H17-7",name:"Swallowing"},
				  {id:"H17-8",name:"Voyeur"},
				  {id:"H17-9",name:"Wetting"},
				  {id:"H2",name:"Blood"},
				  {id:"H2-1",name:"Bloodletting"},
				  {id:"H2-2",name:"Swallowing"},
				  {id:"H3",name:"Breath Control"},
				  {id:"H3-1",name:"Asphyxiation"},
				  {id:"H3-2",name:"Choking"},
				  {id:"H4",name:"Death"},
				  {id:"H4-1",name:"Defilement"},
				  {id:"H4-2",name:"Impalement"},
				  {id:"H4-3",name:"Permanent"},
				  {id:"H5",name:"Drugs"},
				  {id:"H5-1",name:"Addiction"},
				  {id:"H5-2",name:"Alcohol"},
				  {id:"H5-3",name:"Aphrodisiacs"},
				  {id:"H5-4",name:"Hard Drugs"},
				  {id:"H5-5",name:"Smoking"},
				  {id:"H6",name:"Enema"},
				  {id:"H6-1",name:"Clean"},
				  {id:"H6-2",name:"Cum"},
				  {id:"H6-3",name:"Messy"},
				  {id:"H7",name:"Inflation"},
				  {id:"H7-1",name:"Heavy"},
				  {id:"H7-2",name:"Light"},
				  {id:"H7-3",name:"Popping"},
				  {id:"H8",name:"Rape"},
				  {id:"H8-1",name:"Hard Rape"},
				  {id:"H8-2",name:"Pseudo-Rape"},
				  {id:"H9",name:"Torture"},
				  {id:"H9-1",name:"Breast/Nipple"},
				  {id:"H9-2",name:"Burning"},
				  {id:"H9-3",name:"Chemical"},
				  {id:"H9-4",name:"Electro-Torture"},
				  {id:"H9-5",name:"Genital Torture"},
				  {id:"H9-6",name:"Hot/Cold"},
				  {id:"H9-7",name:"Pain"},
				  {id:"H9-8",name:"Sexual"},
				  {id:"H9-9",name:"Starvation"}
			  ]
		  },
		  {
			  categoryCode:"M",
			  categoryTitle:"Role",
			  kinks:[
				  {id:"M1",name:"Bottom"},
				  {id:"M2",name:"Dominant"},
				  {id:"M3",name:"Equal"},
				  {id:"M4",name:"Submissive"},
				  {id:"M5",name:"Switch"},
				  {id:"M6",name:"Top"}
			  ]
		  },
		  {
			  categoryCode:"P",
			  categoryTitle:"Preference",
			  kinks:[
				  {id:"P1",name:"Androgynous"},
				  {id:"P1-1",name:"Trap"},
				  {id:"P1-2",name:"Reverse-Trap"},
				  {id:"P2",name:"Cuntboys"},
				  {id:"P3",name:"Females"},
				  {id:"P4",name:"Hermaphrodites"},
				  {id:"P5",name:"Male Herms"},
				  {id:"P6",name:"Males"},
				  {id:"P7",name:"Shemales"},
				  {id:"P8",name:"Transgender"}
			  ]
		  },
		  {
			  categoryCode:"R",
			  categoryTitle:"Roleplay",
			  kinks:[
				  {id:"R1",name:"Clothing"},
				  {id:"R10",name:"Perspective - Second"},
				  {id:"R11",name:"Perspective - Third"},
				  {id:"R1-1",name:"Boots/Shoes"},
				  {id:"R1-10",name:"Maid"},
				  {id:"R1-11",name:"Naked Apron"},
				  {id:"R1-12",name:"Religious"},
				  {id:"R1-13",name:"Slutty"},
				  {id:"R1-14",name:"Style"},
				  {id:"R1-15",name:"Suits"},
				  {id:"R1-16",name:"Underwear"},
				  {id:"R1-17",name:"Uniforms"},
				  {id:"R1-18",name:"Wedding/Formal"},
				  {id:"R1-19",name:"Stockings"},
				  {id:"R12",name:"Pregnancy"},
				  {id:"R1-2",name:"Costumes"},
				  {id:"R12-1",name:"Birthing"},
				  {id:"R12-2",name:"Breeding"},
				  {id:"R12-3",name:"Extreme Pregnancy"},
				  {id:"R12-4",name:"Impregnation"},
				  {id:"R12-5",name:"Male Pregnancy"},
				  {id:"R12-6",name:"Oviposition"},
				  {id:"R12-7",name:"Pregnant Sex"},
				  {id:"R12-8",name:"Risk of Pregnancy"},
				  {id:"R12-9",name:"Unusual Pregnancy"},
				  {id:"R13",name:"Role Reversal"},
				  {id:"R1-3",name:"Crossdressing"},
				  {id:"R14",name:"Romance"},
				  {id:"R1-4",name:"Glasses"},
				  {id:"R14-1",name:"Cuddling"},
				  {id:"R14-2",name:"Dating"},
				  {id:"R14-3",name:"Kissing"},
				  {id:"R14-4",name:"Marriage"},
				  {id:"R14-5",name:"PDA"},
				  {id:"R14-6",name:"Polygamy"},
				  {id:"R15",name:"RP in RP"},
				  {id:"R1-5",name:"Kimono/Japanese"},
				  {id:"R15-1",name:"Ageplay"},
				  {id:"R15-2",name:"Costumes"},
				  {id:"R15-3",name:"Infantilism"},
				  {id:"R16",name:"Rubber/Latex"},
				  {id:"R1-6",name:"Latex"},
				  {id:"R16-1",name:"Hoods"},
				  {id:"R16-2",name:"Suits"},
				  {id:"R16-3",name:"Toys"},
				  {id:"R17",name:"Sandboxing"},
				  {id:"R1-7",name:"Leather"},
				  {id:"R18",name:"Taboo"},
				  {id:"R1-8",name:"Lingerie"},
				  {id:"R18-1",name:"Adultery"},
				  {id:"R18-2",name:"Age Differences"},
				  {id:"R18-3",name:"Blasphemy"},
				  {id:"R18-4",name:"Incest"},
				  {id:"R18-5",name:"Interracial"},
				  {id:"R18-6",name:"Interspecies"},
				  {id:"R18-7",name:"Orientation Play"},
				  {id:"R18-8",name:"Spanking"},
				  {id:"R19",name:"Teasing"},
				  {id:"R1-9",name:"Masks"},
				  {id:"R19-1",name:"Caressing"},
				  {id:"R19-2",name:"Humiliation"},
				  {id:"R19-3",name:"Tickling"},
				  {id:"R2",name:"Exhibitionism"},
				  {id:"R20",name:"Themed"},
				  {id:"R20-1",name:"Captivity"},
				  {id:"R20-10",name:"School"},
				  {id:"R20-11",name:"Sci-Fi"},
				  {id:"R20-12",name:"Steampunk"},
				  {id:"R20-13",name:"Tribal"},
				  {id:"R20-14",name:"Zero-G"},
				  {id:"R20-2",name:"Fantasy"},
				  {id:"R20-3",name:"Isolation"},
				  {id:"R20-4",name:"Law Enforcement"},
				  {id:"R20-5",name:"Medical"},
				  {id:"R20-6",name:"Office"},
				  {id:"R20-7",name:"Political"},
				  {id:"R20-8",name:"Prostitution"},
				  {id:"R20-9",name:"Religion"},
				  {id:"R21",name:"Unwilling"},
				  {id:"R2-1",name:"Public Nudity"},
				  {id:"R21-1",name:"Blackmail"},
				  {id:"R21-2",name:"Obligation"},
				  {id:"R21-3",name:"Penalty"},
				  {id:"R22",name:"Violence"},
				  {id:"R2-2",name:"Public Sex"},
				  {id:"R22-1",name:"Bladeplay"},
				  {id:"R22-2",name:"Fighting"},
				  {id:"R22-3",name:"Guns"},
				  {id:"R22-4",name:"Wrestling"},
				  {id:"R23",name:"Voyeurism"},
				  {id:"R23-1",name:"Accidental"},
				  {id:"R23-2",name:"Cuckolding"},
				  {id:"R23-3",name:"Spying"},
				  {id:"R3",name:"Food"},
				  {id:"R3-1",name:"Force Feeding"},
				  {id:"R3-2",name:"Nyo/Nan-taimori"},
				  {id:"R3-3",name:"Sweets"},
				  {id:"R3-4",name:"Syrups"},
				  {id:"R3-5",name:"Weight Gain"},
				  {id:"R4",name:"Instant Hookups"},
				  {id:"R5",name:"Long Term"},
				  {id:"R5-1",name:"Grid"},
				  {id:"R5-2",name:"Sandbox"},
				  {id:"R6",name:"Magic"},
				  {id:"R6-1",name:"Background"},
				  {id:"R6-2",name:"Magic Sex"},
				  {id:"R6-3",name:"Potions"},
				  {id:"R7",name:"Mind Control"},
				  {id:"R7-1",name:"Body Control"},
				  {id:"R7-2",name:"Direct Control"},
				  {id:"R7-3",name:"Hypnotism"},
				  {id:"R7-4",name:"Memory Wipe"},
				  {id:"R7-5",name:"Programming"},
				  {id:"R7-6",name:"Suggestion"},
				  {id:"R7-7",name:"Training"},
				  {id:"R8",name:"Nonsexual"},
				  {id:"R9",name:"Perspective - First"}
			  ]
		  },
		  {
			  categoryCode:"S",
			  categoryTitle:"Sex",
			  kinks:[
				  {id:"S1",name:"Anal Sex"},
				  {id:"S10",name:"Oral Sex"},
				  {id:"S10-1",name:"Autocunnilingus"},
				  {id:"S10-2",name:"Autofellatio"},
				  {id:"S10-3",name:"Cunnilingus"},
				  {id:"S10-4",name:"Face-Fucking"},
				  {id:"S10-5",name:"Fellatio"},
				  {id:"S10-6",name:"Throat Penetration"},
				  {id:"S10-7",name:"Virginity"},
				  {id:"S11",name:"Penis Sex"},
				  {id:"S1-1",name:"Ass Worship"},
				  {id:"S11-1",name:"Docking"},
				  {id:"S11-2",name:"Frottage"},
				  {id:"S11-3",name:"Handjob"},
				  {id:"S11-4",name:"Sounding"},
				  {id:"S11-5",name:"Cock Worship"},
				  {id:"S11-6",name:"Ball Worship"},
				  {id:"S12",name:"Toys"},
				  {id:"S1-2",name:"Fisting"},
				  {id:"S12-1",name:"Anal Beads"},
				  {id:"S12-2",name:"Dildos"},
				  {id:"S12-3",name:"Sex Machines"},
				  {id:"S12-4",name:"Strap-ons"},
				  {id:"S12-5",name:"Vibrators"},
				  {id:"S13",name:"Vaginal Sex"},
				  {id:"S1-3",name:"Gaping"},
				  {id:"S13-1",name:"Cervical Penetration"},
				  {id:"S13-10",name:"Virginity"},
				  {id:"S13-2",name:"Fingering"},
				  {id:"S13-3",name:"Fisting"},
				  {id:"S13-4",name:"Gaping"},
				  {id:"S13-5",name:"Penetration"},
				  {id:"S13-6",name:"Pussy Worship"},
				  {id:"S13-7",name:"Squirting"},
				  {id:"S13-8",name:"Tribadism"},
				  {id:"S13-9",name:"Urethra Penetration"},
				  {id:"S1-4",name:"Hotdogging"},
				  {id:"S1-5",name:"Pegging"},
				  {id:"S1-6",name:"Penetration"},
				  {id:"S1-7",name:"Rimming"},
				  {id:"S1-8",name:"Training"},
				  {id:"S1-9",name:"Virginity"},
				  {id:"S2",name:"Biting"},
				  {id:"S2-1",name:"Marking"},
				  {id:"S3",name:"Breasts"},
				  {id:"S3-1",name:"Breast Worship"},
				  {id:"S3-2",name:"Docking"},
				  {id:"S3-3",name:"Fondling"},
				  {id:"S3-4",name:"Lactation"},
				  {id:"S3-5",name:"Nipple Penetration"},
				  {id:"S3-6",name:"Titfucking"},
				  {id:"S4",name:"Clothed Sex"},
				  {id:"S5",name:"Condoms"},
				  {id:"S5-1",name:"Breaking"},
				  {id:"S5-2",name:"Swallowing After"},
				  {id:"S6",name:"Cumplay"},
				  {id:"S6-1",name:"Bukkake"},
				  {id:"S6-10",name:"Creampie"},
				  {id:"S6-11",name:"Internal"},
				  {id:"S6-2",name:"Cum Bath"},
				  {id:"S6-3",name:"Cum Diet"},
				  {id:"S6-4",name:"Inflation(Light)"},
				  {id:"S6-5",name:"Inflation(Medium)"},
				  {id:"S6-6",name:"Inflation(Heavy)"},
				  {id:"S6-7",name:"Large Quantities"},
				  {id:"S6-8",name:"Swallowing"},
				  {id:"S6-9",name:"Unusual Semen"},
				  {id:"S7",name:"Exotic"},
				  {id:"S7-1",name:"Armpit Sex"},
				  {id:"S7-10",name:"Other"},
				  {id:"S7-11",name:"Sleep Sex"},
				  {id:"S7-2",name:"Ear Penetration"},
				  {id:"S7-3",name:"Ear Play"},
				  {id:"S7-4",name:"Eye Penetration"},
				  {id:"S7-5",name:"Foot Fetish"},
				  {id:"S7-6",name:"Footjobs"},
				  {id:"S7-7",name:"Hairjob"},
				  {id:"S7-8",name:"Navel Penetration"},
				  {id:"S7-9",name:"Navel Play"},
				  {id:"S8",name:"Masturbation"},
				  {id:"S8-1",name:"In Scenes"},
				  {id:"S8-2",name:"Mutual Masturbation"},
				  {id:"S8-3",name:"Secret"},
				  {id:"S9",name:"Multiple Penetration"},
				  {id:"S9-1",name:"3+ Penetration"},
				  {id:"S9-2",name:"All The Way Through"},
				  {id:"S9-3",name:"Double Penetration"},
				  {id:"S9-4",name:"Gangbang"}
			  ]
		  },
		  {
			  categoryCode:"T",
			  categoryTitle:"Body Types",
			  kinks:[
				  {id:"T1",name:"Animal"},
				  {id:"T10",name:"Giant/Macro"},
				  {id:"T11",name:"Head Hair"},
				  {id:"T1-1",name:"Aquatic"},
				  {id:"T11-1",name:"Bald"},
				  {id:"T11-2",name:"Short"},
				  {id:"T11-3",name:"Long"},
				  {id:"T11-4",name:"Very Long"},
				  {id:"T11-5",name:"Exotic"},
				  {id:"T12",name:"Hirsute"},
				  {id:"T1-2",name:"Avian"},
				  {id:"T12-1",name:"Armpit Hair"},
				  {id:"T12-2",name:"Beards"},
				  {id:"T12-3",name:"Body Hair"},
				  {id:"T12-4",name:"Pubic Hair"},
				  {id:"T13",name:"Humanoid"},
				  {id:"T1-3",name:"Draconic"},
				  {id:"T13-1",name:"Angel"},
				  {id:"T13-2",name:"Demon"},
				  {id:"T13-3",name:"Elvish"},
				  {id:"T13-4",name:"Human"},
				  {id:"T14",name:"Large Anatomy"},
				  {id:"T1-4",name:"Equine"},
				  {id:"T14-1",name:"Chubby"},
				  {id:"T14-2",name:"Large Asses"},
				  {id:"T14-3",name:"Large Balls"},
				  {id:"T14-4",name:"Large Breasts"},
				  {id:"T14-5",name:"Large Cocks"},
				  {id:"T14-6",name:"Muscle"},
				  {id:"T15",name:"Sexless"},
				  {id:"T1-5",name:"Insect/Arachnid"},
				  {id:"T15-1",name:"Desexed"},
				  {id:"T15-2",name:"Eunuch"},
				  {id:"T16",name:"Shapeshifters"},
				  {id:"T1-6",name:"Pokemon/Digimon"},
				  {id:"T16-1",name:"Multiple-Form"},
				  {id:"T16-2",name:"Single-Form"},
				  {id:"T16-3",name:"Unwilling"},
				  {id:"T16-4",name:"Willing"},
				  {id:"T17",name:"Small Anatomy"},
				  {id:"T1-7",name:"Quadruped"},
				  {id:"T17-1",name:"Extreme Tightness"},
				  {id:"T17-2",name:"Flat Chest"},
				  {id:"T17-3",name:"Small Breasts"},
				  {id:"T17-4",name:"Small Cocks"},
				  {id:"T18",name:"Tails"},
				  {id:"T1-8",name:"Serpentine"},
				  {id:"T18-1",name:"Fluffy"},
				  {id:"T18-2",name:"Prehensile"},
				  {id:"T19",name:"Taurs/Hybrid"},
				  {id:"T19-1",name:"Aquatic"},
				  {id:"T19-2",name:"Avian"},
				  {id:"T19-3",name:"Insect/Arachnid"},
				  {id:"T19-4",name:"Quadruped"},
				  {id:"T19-5",name:"Serpentine"},
				  {id:"T2",name:"Animal Anatomy"},
				  {id:"T20",name:"Tentacles"},
				  {id:"T20-1",name:"Consentacles"},
				  {id:"T21",name:"Twins/Clones"},
				  {id:"T2-1",name:"Barbed Cocks"},
				  {id:"T22",name:"Wings"},
				  {id:"T2-2",name:"Bestial Cocks"},
				  {id:"T22-1",name:"Batlike"},
				  {id:"T22-2",name:"Fairy"},
				  {id:"T22-3",name:"Feathery"},
				  {id:"T23",name:"Young Partners"},
				  {id:"T2-3",name:"Knotted Cocks"},
				  {id:"T23-1",name:"Preteen"},
				  {id:"T23-2",name:"Pubescent"},
				  {id:"T23-3",name:"Teenage"},
				  {id:"T24",name:"Decorations"},
				  {id:"T2-4",name:"Sheaths"},
				  {id:"T24-1",name:"Marks"},
				  {id:"T24-2",name:"Scars"},
				  {id:"T24-3",name:"Paint"},
				  {id:"T24-4",name:"Piercings"},
				  {id:"T24-5",name:"Tattoos"},
				  {id:"T2-5",name:"Udders"},
				  {id:"T3",name:"Anthro"},
				  {id:"T3-1",name:"Equine"},
				  {id:"T3-2",name:"Feathers"},
				  {id:"T3-3",name:"Fur"},
				  {id:"T3-4",name:"Kemonomimi"},
				  {id:"T3-5",name:"Muzzles"},
				  {id:"T3-6",name:"Pokemorph"},
				  {id:"T3-7",name:"Scales"},
				  {id:"T4",name:"Artificial"},
				  {id:"T4-1",name:"Dolljoints"},
				  {id:"T4-2",name:"Robots/Cyborgs"},
				  {id:"T5",name:"Elderly Partners"},
				  {id:"T5-1",name:"Middle Age"},
				  {id:"T5-2",name:"Elderly"},
				  {id:"T6",name:"Exotic Anatomy"},
				  {id:"T6-1",name:"Dicknipples"},
				  {id:"T6-2",name:"Heterochromia"},
				  {id:"T6-3",name:"Missing Parts"},
				  {id:"T6-4",name:"Multiple Breasts"},
				  {id:"T6-5",name:"Multiple Genitalia"},
				  {id:"T6-6",name:"Out of Place"},
				  {id:"T6-7",name:"Prehensile Cocks"},
				  {id:"T7",name:"Exotic Material"},
				  {id:"T7-1",name:"Ghostly"},
				  {id:"T7-2",name:"Latex"},
				  {id:"T7-3",name:"Metal"},
				  {id:"T7-4",name:"Rubber"},
				  {id:"T7-5",name:"Stone"},
				  {id:"T7-6",name:"Water/Liquid"},
				  {id:"T8",name:"Exotic Species"},
				  {id:"T8-1",name:"Alien/Xeno"},
				  {id:"T8-2",name:"Blob"},
				  {id:"T8-3",name:"Eldritch"},
				  {id:"T8-4",name:"Fantastical"},
				  {id:"T8-5",name:"Monstrous"},
				  {id:"T8-6",name:"Plants"},
				  {id:"T9",name:"Extreme Anatomy"},
				  {id:"T9-1",name:"Huge Ass"},
				  {id:"T9-2",name:"Massive Breasts"},
				  {id:"T9-3",name:"Massive Cocks"},
				  {id:"T9-4",name:"Obesity"}
			  ]
		  }
	  ]
	 );
